global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'healthmug-api-lens'
    static_configs:
      - targets: ['host.docker.internal:3000']
    scrape_interval: 30s
  
  - job_name: 'python-analytics'
    static_configs:
      - targets: ['host.docker.internal:9877']
    scrape_interval: 30s
  
  - job_name: 'stability-metrics'
    static_configs:
      - targets: ['host.docker.internal:9878']
    scrape_interval: 60s
  
  - job_name: 'multi-site-metrics'
    static_configs:
      - targets: ['host.docker.internal:9879']
    scrape_interval: 30s